
import { Language } from '../types';

export const TEXT = {
  en: {
    appTitle: 'Financial',
    appTitleSuffix: 'Health',
    editInputs: 'Edit Inputs',
    viewReport: 'View Report',
    dashboard: 'Dashboard',
    methodology: 'Methodology',
    
    // Input Form
    inputTitle: 'Diagnostic Quick Check',
    inputSubtitle: 'Input your financial details below to receive a deterministic health score and action plan.',
    inputHeader: 'Financial Data Input',
    inputHeaderDesc: 'Enter your data or load a case study.',
    loadDemo: 'Load Demo',
    sectionPersonal: '1. Personal & Family Finances',
    sectionBusiness: '2. Business Financials',
    sectionAdvanced: '3. Advanced / Balance Sheet (Optional)',
    runDiagnostic: 'Run Diagnostic Analysis',
    
    // Field Labels
    monthlyIncome: 'Monthly Household Income',
    monthlyExpenses: 'Monthly Expenses',
    cashAvailable: 'Cash / Emergency Fund',
    monthlyDebtPayments: 'Monthly Debt Payments',
    revenue: 'Monthly Revenue',
    payroll: 'Total Payroll',
    cogs: 'COGS (Cost of Goods)',
    opCosts: 'Operating Costs (OpEx)',
    businessCashReserves: 'Business Cash Reserves',
    currentAssets: 'Current Assets',
    currentLiabilities: 'Current Liabilities',
    topClientShare: 'Top Client Share (0-1)',

    // Dashboard
    scoreTitle: 'Financial Health Score',
    metricBalance: 'Metric Balance',
    scenarioSimulator: 'Scenario Simulator',
    historicalTrends: 'Historical Trends',
    diagnosticBreakdown: 'Diagnostic Breakdown',
    actionPlan: 'Deterministic Action Plan',
    actionPlanDesc: 'Generated based on critical thresholds found in your data.',
    executionChecklist: 'Execution Checklist',
    noActions: 'No critical actions detected. Maintain current discipline.',
    
    // Scenario
    revenueAdj: 'Revenue Adjustment',
    cogsAdj: 'COGS Adjustment',
    payrollAdj: 'Payroll Adjustment',
    opexAdj: 'OpEx Adjustment',
    projScore: 'Projected Score',
    projRunway: 'Projected Runway',
    scenarioNote: 'Variables are independent. Increasing revenue does not automatically increase COGS in this simulation.',

    // Report
    reportTitle: 'Financial Health Report',
    reportSubtitle: 'Deterministic Diagnostic v1.0',
    generatedBy: 'Generated by FHD Platform',
    execSummary: '1. Executive Summary',
    keyDiagnosis: 'Key Diagnosis',
    metricAnalysis: '2. Metric Analysis',
    recActions: '3. Recommended Actions',
    auditTrail: 'Appendix: Input Data Audit',
    downloadPdf: 'Download PDF',
    print: 'Print',
    generating: 'Generating...',
    
    // Table Headers
    thMetric: 'Metric',
    thScore: 'Score',
    thValue: 'Value',
    thAssessment: 'Assessment',

    // Yearly Summary
    yearlySummary: 'Yearly Financial Summary (Annualized)',
    annualRevenue: 'Annual Revenue',
    annualCOGS: 'Annual COGS',
    annualPayroll: 'Annual Payroll',
    annualOpEx: 'Annual OpEx',
    annualNetProfit: 'Annual Net Profit',

    // Insights
    insightsTitle: 'Methodology & Benchmarks',
    insightsSubtitle: 'Understanding the algorithms behind your score.',
    formula: 'Formula',
    benchmark: 'Benchmark',
    whyItMatters: 'Why it matters',
    
    methodologyContent: {
      cfh: {
        title: 'Cashflow Health',
        formula: 'Net Cashflow = Income - Expenses',
        benchmark: 'Positive (> 0)',
        why: 'The lifeblood of personal finance. Without positive cashflow, debt accumulation is inevitable.'
      },
      dsr: {
        title: 'Debt Service Ratio (DSR)',
        formula: 'Monthly Debt Payments / Monthly Income',
        benchmark: '< 35% is Ideal, > 50% is Critical',
        why: 'Measures your ability to pay off debt. High DSR limits your borrowing power and increases bankruptcy risk.'
      },
      efc: {
        title: 'Emergency Fund Coverage',
        formula: 'Total Liquid Cash / Monthly Expenses',
        benchmark: '> 6 Months',
        why: 'A buffer against unexpected life events (job loss, medical). Prevents you from liquidating assets at a loss.'
      },
      runway: {
        title: 'Business Runway',
        formula: 'Cash Reserves / Monthly Burn Rate',
        benchmark: '> 12 Months',
        why: 'How long the business can survive without new revenue. Crucial for stability during market downturns.'
      },
      profit: {
        title: 'Net Profit Margin',
        formula: '(Revenue - All Expenses) / Revenue',
        benchmark: '> 15%',
        why: 'Indicates efficiency. Low margin businesses are fragile to price wars or cost increases.'
      },
      payroll: {
        title: 'Payroll Efficiency',
        formula: 'Total Payroll / Revenue',
        benchmark: '< 30% for High Growth, < 50% for Service',
        why: 'Human capital is usually the biggest cost. If it exceeds 50%, the business works for the employees, not the owner.'
      },
      liquidity: {
        title: 'Current Ratio',
        formula: 'Current Assets / Current Liabilities',
        benchmark: '> 1.5',
        why: 'Short-term solvency. Can the business pay its bills due in the next 12 months?'
      }
    }
  },
  id: {
    appTitle: 'Kesehatan',
    appTitleSuffix: 'Finansial',
    editInputs: 'Ubah Data',
    viewReport: 'Lihat Laporan',
    dashboard: 'Dasbor',
    methodology: 'Metodologi',
    
    // Input Form
    inputTitle: 'Cek Diagnosa Cepat',
    inputSubtitle: 'Masukkan detail keuangan Anda di bawah untuk mendapatkan skor kesehatan dan rencana aksi.',
    inputHeader: 'Input Data Keuangan',
    inputHeaderDesc: 'Masukkan data Anda atau muat studi kasus.',
    loadDemo: 'Muat Demo',
    sectionPersonal: '1. Keuangan Pribadi & Keluarga',
    sectionBusiness: '2. Keuangan Bisnis',
    sectionAdvanced: '3. Lanjutan / Neraca (Opsional)',
    runDiagnostic: 'Jalankan Analisis Diagnosa',
    
    // Field Labels
    monthlyIncome: 'Pendapatan Rumah Tangga Bulanan',
    monthlyExpenses: 'Pengeluaran Bulanan',
    cashAvailable: 'Kas Tunai / Dana Darurat',
    monthlyDebtPayments: 'Cicilan Utang Bulanan',
    revenue: 'Omzet / Revenue Bulanan',
    payroll: 'Total Gaji Pegawai (Payroll)',
    cogs: 'HPP (Harga Pokok Penjualan)',
    opCosts: 'Biaya Operasional (OpEx)',
    businessCashReserves: 'Cadangan Kas Bisnis',
    currentAssets: 'Aset Lancar',
    currentLiabilities: 'Utang Lancar',
    topClientShare: 'Porsi Klien Terbesar (0-1)',

    // Dashboard
    scoreTitle: 'Skor Kesehatan Finansial',
    metricBalance: 'Keseimbangan Metrik',
    scenarioSimulator: 'Simulator Skenario',
    historicalTrends: 'Tren Historis',
    diagnosticBreakdown: 'Rincian Diagnosa',
    actionPlan: 'Rencana Aksi Deterministik',
    actionPlanDesc: 'Dihasilkan berdasarkan ambang batas kritis yang ditemukan dalam data Anda.',
    executionChecklist: 'Daftar Periksa Eksekusi',
    noActions: 'Tidak ada tindakan kritis yang terdeteksi. Pertahankan disiplin saat ini.',
    
    // Scenario
    revenueAdj: 'Penyesuaian Revenue',
    cogsAdj: 'Penyesuaian HPP',
    payrollAdj: 'Penyesuaian Gaji',
    opexAdj: 'Penyesuaian OpEx',
    projScore: 'Proyeksi Skor',
    projRunway: 'Proyeksi Runway',
    scenarioNote: 'Variabel bersifat independen. Meningkatkan revenue tidak secara otomatis meningkatkan HPP dalam simulasi ini.',

    // Report
    reportTitle: 'Laporan Kesehatan Finansial',
    reportSubtitle: 'Diagnosa Deterministik v1.0',
    generatedBy: 'Dibuat oleh Platform FHD',
    execSummary: '1. Ringkasan Eksekutif',
    keyDiagnosis: 'Diagnosa Utama',
    metricAnalysis: '2. Analisis Metrik',
    recActions: '3. Rekomendasi Aksi',
    auditTrail: 'Lampiran: Audit Data Input',
    downloadPdf: 'Unduh PDF',
    print: 'Cetak',
    generating: 'Memproses...',
    
    // Table Headers
    thMetric: 'Metrik',
    thScore: 'Skor',
    thValue: 'Nilai',
    thAssessment: 'Penilaian',

    // Yearly Summary
    yearlySummary: 'Ringkasan Keuangan Tahunan (Disetahunkan)',
    annualRevenue: 'Omzet Tahunan',
    annualCOGS: 'HPP Tahunan',
    annualPayroll: 'Gaji Tahunan',
    annualOpEx: 'OpEx Tahunan',
    annualNetProfit: 'Laba Bersih Tahunan',

    // Insights
    insightsTitle: 'Metodologi & Benchmark',
    insightsSubtitle: 'Memahami algoritma di balik skor Anda.',
    formula: 'Rumus',
    benchmark: 'Tolak Ukur',
    whyItMatters: 'Mengapa ini penting',

    methodologyContent: {
      cfh: {
        title: 'Kesehatan Arus Kas',
        formula: 'Arus Kas Bersih = Pendapatan - Pengeluaran',
        benchmark: 'Positif (> 0)',
        why: 'Jantung keuangan pribadi. Tanpa arus kas positif, penumpukan utang tidak terhindarkan.'
      },
      dsr: {
        title: 'Rasio Cicilan Utang (DSR)',
        formula: 'Cicilan Utang Bulanan / Pendapatan Bulanan',
        benchmark: '< 35% Ideal, > 50% Kritis',
        why: 'Mengukur kemampuan membayar utang. DSR tinggi membatasi kemampuan meminjam dan meningkatkan risiko kebangkrutan.'
      },
      efc: {
        title: 'Cakupan Dana Darurat',
        formula: 'Total Kas Likuid / Pengeluaran Bulanan',
        benchmark: '> 6 Bulan',
        why: 'Penyangga terhadap kejadian tak terduga (PHK, sakit). Mencegah likuidasi aset dengan harga rugi.'
      },
      runway: {
        title: 'Runway Bisnis',
        formula: 'Cadangan Kas / Burn Rate Bulanan',
        benchmark: '> 12 Bulan',
        why: 'Berapa lama bisnis bertahan tanpa revenue baru. Krusial untuk stabilitas saat pasar lesu.'
      },
      profit: {
        title: 'Margin Laba Bersih',
        formula: '(Revenue - Semua Biaya) / Revenue',
        benchmark: '> 15%',
        why: 'Indikator efisiensi. Bisnis margin rendah sangat rapuh terhadap perang harga atau kenaikan biaya.'
      },
      payroll: {
        title: 'Efisiensi Gaji',
        formula: 'Total Gaji / Revenue',
        benchmark: '< 30% untuk Growth, < 50% untuk Jasa',
        why: 'Modal manusia biasanya biaya terbesar. Jika > 50%, bisnis bekerja untuk karyawan, bukan pemilik.'
      },
      liquidity: {
        title: 'Rasio Lancar',
        formula: 'Aset Lancar / Utang Lancar',
        benchmark: '> 1.5',
        why: 'Solvabilitas jangka pendek. Bisakah bisnis membayar tagihan yang jatuh tempo dalam 12 bulan?'
      }
    }
  }
};